excerpt_separator: ""
pygments: false
markdown: kramdown
url: http://ohyran.github.io
title: Public Memo
email: ohyran@gmail.com
author: Jens Reuterberg
description: A place to put all thoughts.
paginate: 10
google_analytics: 
